### ISSUE TITLE
BookingActions call in eigene Action

### ISSUE THREAD

**Issue by diegosteiner** [diegosteiner/heimv#293]
## Tasks

- [x] create controller, actions, and routes
- [ ] change actions buttons to  post to new controller
- [ ] create action for state_transition
- [ ] allow params for actions
- [ ] allow render step for actions

**Comment by diegosteiner** [comment]
Für Storno zum beispiel
